### ISSUE TITLE
Highlighting for block comments

### ISSUE THREAD

**Issue by VeliKangas** [Godot-dev/mosel-support#1]
Hello!

I've been using this extension a bit recently, and I noticed that it doesn't support highlighting block comments marked by `(!` and `!)` in Mosel. Is there a specific reason for this, or could the support be added? Looks like there's already a place in the language configuration json where it could be defined, maybe it's that easy?

Thanks!
-Veli

**Comment by Godot-dev** [comment]
Hi! 
It was sadly a little harder than this, but I solved it ! Funny to see that someone is using this thing I created a long time ago during my studies just because it was frustrating for me to not be able to use syntax highlighting on mosel during my lessons^^

Thank you for the report !
Eden

**Comment by VeliKangas** [comment]
Thanks for figuring it out!
My team is starting to work with Mosel and we'd prefer using VS Code for the easy version control and such. We might even consider building a simple formatter for the language, although it remains to be seen if that's realistic for us. 😄
